FROM node:22-alpine AS runner
WORKDIR /app

ARG NEXT_PUBLIC_BASE_PATH
ENV NODE_ENV=production
ENV NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH}

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY openbox-x-copilotkit/public ./public
COPY --chown=nextjs:nodejs openbox-x-copilotkit/.next/standalone ./
COPY --chown=nextjs:nodejs openbox-x-copilotkit/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
